### PR TITLE
change name and add controller folder

### PR DESCRIPTION
**Pull request by LeeMoTakito**
Sorry, I made the named module instead of models and I changed it.

### CODE REVIEW

**Comment by LeeMoTakito** [comment]
I forgot to run the build and I did. Would you check fo me

**Comment by RylanTech** [comment]
I'm not sure I understand about the build, we can build it ourselves I don't think that it is important that we commit the build.

**Review by akinsman22 — CHANGES_REQUESTED** [review]
Momo, I agree with Rylan. Could we put Build in a gitignore file? We would need to do that on our local copies and not have on a Dev ones. Church controller is empty?

**Comment by LeeMoTakito** [comment]
Ok, I make get ignored. Did you understand the name of the file module to change to models?

**Pull request merged**
